name: 'Google Drive upload'
description: 'Upload a file to Google Drive using a service account'
inputs:
  credentials:
    description: 'Google service account credentials'
    required: true
  parent_folder_id:
    description: 'Google Drive folder ID to upload the file to'
    required: true
  targets:
    description: 'List of local paths to the file to upload'
    required: true
  overwrite:
    description: 'Whether to overwrite an existing file with the same name.'
    required: false
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: purple
